name: Crear EXE de Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar PyInstaller
        run: python -m pip install pyinstaller

      - name: Crear EXE portable
        run: pyinstaller --noconfirm --onefile --windowed --name RegistroVentas app.py

      - name: Subir EXE
        uses: actions/upload-artifact@v4
        with:
          name: RegistroVentas-Windows
          path: dist/RegistroVentas.exe
